### ISSUE TITLE
Make the tool to get filenames by prefix

### ISSUE THREAD

**Issue by he7d3r** [Krinkle/mw-tool-usage#2]
It seems most people who is using a hack to workaround [phab:T35355](https://phabricator.wikimedia.org/T35355), prefixes the filenames with some string.

Maybe this tool could store just the list of prefixes, and then query the database or API to get all filenames with that prefix (instead of listing each file individually in a JSON file)?

**Comment by Krinkle** [comment]
I considered that but didn't do it. A few reasons:
- Provide better labels.<br>We could require tracker files to have better names, but we tend to have different conventions for file names and display titles.
- Avoid abuse.<br>We don't want additional files to show up we don't own.
- Allow hiding trackers.<br>When you prefer not to have it published (yet), or no more. (Could be worked around by not-creating/deleting the file on Commons.)
- Extensibility.<br>We might want to link to documentation pages later and other associated (optional) data.
- Performance.<br>Knowing the query makes it easier to cache API queries.
- Simplicity.<br>To do it right, one would want to ensure that the matched pages are redirects and transclude `{{GlobalJsUsage}}`, which is hard to do without querying the database, and I'd like this tool to remain portable using the API. If it would use prefixes on globalusage, it would depend in database access.

However, patches are welcome as pull requests; and I'm willing to drop all the above as long as it doesn't use the database (an API query for allpages/prefixsearch could work).
